create table if not exists public.site_page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page_path text not null,
  page_url text,
  referrer text,
  country text,
  region text,
  city text,
  user_agent text,
  visitor_id text not null,
  session_id text not null
);

create index if not exists idx_site_page_views_created_at
  on public.site_page_views (created_at desc);

create index if not exists idx_site_page_views_page_path
  on public.site_page_views (page_path);

create index if not exists idx_site_page_views_country
  on public.site_page_views (country);

create index if not exists idx_site_page_views_visitor_id
  on public.site_page_views (visitor_id);

alter table public.site_page_views enable row level security;
