create table if not exists public.lead_captures (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null unique,
  source text not null default 'website_newsletter',
  consent_marketing boolean not null default false,
  consent_timestamp timestamptz not null default now()
);

create table if not exists public.lifecycle_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  visitor_id text,
  session_id text,
  page_path text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_lifecycle_events_created_at
  on public.lifecycle_events (created_at desc);

create index if not exists idx_lifecycle_events_event_name
  on public.lifecycle_events (event_name);

alter table public.lead_captures enable row level security;
alter table public.lifecycle_events enable row level security;

revoke all on table public.lead_captures from anon, authenticated;
revoke all on table public.lifecycle_events from anon, authenticated;
grant select, insert, update on table public.lead_captures to service_role;
grant insert on table public.lifecycle_events to service_role;
