create table if not exists public.lifecycle_followup_jobs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  status text not null default 'pending',
  job_type text not null,
  user_email text,
  session_id text,
  visitor_id text,
  payload jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null,
  sent_at timestamptz
);

create index if not exists idx_lifecycle_followup_jobs_status_scheduled
  on public.lifecycle_followup_jobs (status, scheduled_for);

alter table public.lifecycle_followup_jobs enable row level security;
revoke all on table public.lifecycle_followup_jobs from anon, authenticated;
grant select, insert, update on table public.lifecycle_followup_jobs to service_role;
